# Modelos e Estratégias de Trading
## Comportamento do Retorno dos Ativos

Uirá Caiado. 07 de Agosto, 2016

**Resumo**

*Bla bla.*

## 1. Introdução

Nesta sessão vamos ...




## 2. Estatísticas de Retornos Financeiros

Nesta primeira parte o objetivo é estudar as características estatísticas das distri- buições de retornos logarítmicos de cinco diferentes índices de ações.

In [1]:
from pandas_datareader import data, wb
import pandas as pd

In [2]:
d_data = {}
for s_key in ['^GSPC','^GDAXI', '^N225', '^BVSP', '^FTAS']:
    df = data.get_data_yahoo(s_key)
    d_data[s_key] = df

RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv

In [3]:
d_data.keys()

['^N225', '^GSPC', '^BVSP', '^GDAXI']

In [6]:
import Quandl as quandl
data = quandl.get("YAHOO/INDEX_FTAS")
data.tail()

DatasetNotFound: Dataset not found. Check Quandl code: YAHOO/INDEX_FTAS for errors

In [7]:
quandl.get("GOOG/LON_FTAS")

              Open    High     Low   Close     Volume
Date
2009-12-01    0.00    0.00    0.00  273.00   178696.0
2009-12-02     NaN     NaN     NaN  273.00        0.0
2009-12-03     NaN     NaN     NaN  273.00        0.0
2009-12-04     NaN     NaN     NaN  273.00        0.0
2009-12-07     NaN     NaN     NaN  273.00        0.0
2009-12-08     NaN     NaN     NaN  273.00        0.0
2009-12-09     NaN     NaN     NaN  273.00        0.0
2009-12-10     NaN     NaN     NaN  273.00        0.0
2009-12-11     NaN     NaN     NaN  273.00        0.0
2009-12-14     NaN     NaN     NaN  273.00        0.0
2009-12-15     NaN     NaN     NaN  273.00        0.0
2009-12-16     NaN     NaN     NaN  273.00        0.0
2009-12-17     NaN     NaN     NaN  273.00        0.0
2009-12-18     NaN     NaN     NaN  273.00        0.0
2009-12-21     NaN     NaN     NaN  273.00        0.0
2009-12-22     NaN     NaN     NaN  273.00        0.0
2009-12-23  279.48  279.48  279.48  279.48     1500.0
2009-12-24     NaN     NaN     NaN  279.48        0.0
2009-12-25     NaN     NaN     NaN  279.48        0.0
2009-12-28     NaN     NaN     NaN  279.48        0.0
2009-12-29     NaN     NaN     NaN  279.48        0.0
2009-12-30     NaN     NaN     NaN  279.48        0.0
2009-12-31     NaN     NaN     NaN  279.48        0.0
2010-01-01     NaN     NaN     NaN  279.48        0.0
2010-01-04     NaN     NaN     NaN  279.48        0.0
2010-01-05     NaN     NaN     NaN  279.48        0.0
2010-01-06     NaN     NaN     NaN  279.48        0.0
2010-01-07    0.00    0.00    0.00  285.61  1321968.0
2010-01-08     NaN     NaN     NaN  285.61        0.0
2010-01-11     NaN     NaN     NaN  285.61        0.0
...            ...     ...     ...     ...        ...
2012-06-18     NaN     NaN     NaN  283.50        0.0
2012-06-19     NaN     NaN     NaN  283.50        0.0
2012-06-20     NaN     NaN     NaN  283.50        0.0
2012-06-21     NaN     NaN     NaN  283.50        0.0
2012-06-22     NaN     NaN     NaN  283.50        0.0
2012-06-25     NaN     NaN     NaN  283.50        0.0
2012-06-26     NaN     NaN     NaN  283.50        0.0
2012-06-27     NaN     NaN     NaN  283.50        0.0
2012-06-28     NaN     NaN     NaN  283.50        0.0
2012-06-29     NaN     NaN     NaN  283.50        0.0
2012-07-02     NaN     NaN     NaN  283.50        0.0
2012-07-03     NaN     NaN     NaN  283.50        0.0
2012-07-04     NaN     NaN     NaN  283.50        0.0
2012-07-05  304.40  306.70  302.56  305.00     1629.0
2012-07-06     NaN     NaN     NaN  305.00        0.0
2012-07-09     NaN     NaN     NaN  305.00        0.0
2012-07-10  300.50  300.50  300.50  300.50     2721.0
2012-07-11     NaN     NaN     NaN  300.50        0.0
2012-07-12     NaN     NaN     NaN  300.50        0.0
2012-07-13     NaN     NaN     NaN  300.50        0.0
2012-07-16     NaN     NaN     NaN  300.50        0.0
2012-07-17     NaN     NaN     NaN  300.50        0.0
2012-07-18     NaN     NaN     NaN  300.50        0.0
2012-07-19     NaN     NaN     NaN  300.50        0.0
2012-07-20     NaN     NaN     NaN  300.50        0.0
2012-07-23     NaN     NaN     NaN  300.50        0.0
2012-07-24     NaN     NaN     NaN  300.50        0.0
2012-07-25     NaN     NaN     NaN  300.50        0.0
2012-07-26     NaN     NaN     NaN  300.50        0.0
2012-07-27     NaN     NaN     NaN  300.50        0.0

[335 rows x 5 columns]

## 3. Replicação do Índice Bovespa

Nesta segunda parte o objetivo é praticar a agregação transversal de retornos financeiros através da replicação de um índice de ações. Neste caso o objetivo é a replicação do Índice Bovespa (IBOV) através dos retornos individuais das ações compõem o índice.

## 4. Conclusão

Bla bla bla.  

## 5. Últimas Considerações

Bla bla bla.

*Style notebook and change matplotlib defaults*

In [2]:
#loading style sheet
from IPython.core.display import HTML
HTML(open('ipython_style.css').read())

In [3]:
#changing matplotlib defaults
%matplotlib inline
import seaborn as sns
sns.set_palette("deep", desat=.6)
sns.set_context(rc={"figure.figsize": (8, 4)})
sns.set_style("whitegrid")
sns.set_palette(sns.color_palette("PuBuGn_d", 10))